version: '3.7'

networks:
  net:
    driver: bridge

x-airflow-common:
  &airflow-common
  image: airflow-fia:latest
  environment:
      LOAD_EX: y
      EXECUTOR: Local
      FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      JAVA_HOME: /usr
  volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
  networks:
      - net

services:
    airflow_webserver:
        <<: *airflow-common
        depends_on:
            postgres:
               condition: service_healthy
        hostname: airflow_webserver
        container_name: airflow_webserver
        command:
            - webserver
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always
        ports:
            - 8080:8080

    airflow_scheduler:
        <<: *airflow-common
        depends_on:
            - airflow_webserver
        hostname: airflow_scheduler
        container_name: airflow_scheduler
        command:
            - scheduler
        healthcheck:
            test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always

    postgres:
        image: postgres:9.6
        hostname: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        networks:
            - net 

    minio:
        image: minio/minio:latest
        hostname: minio
        container_name: minio
        command: server /data --console-address ":9001"
        restart: always
        environment:
          - MINIO_ROOT_USER=aula_fia 
          - MINIO_ROOT_PASSWORD=aula_fia@123
        volumes:
          - ./minio:/data
        networks:
          - net
        ports:
          - 9000:9000
          - 9001:9001

    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      restart: always
      hostname: zookeeper
      container_name: zookeeper
      networks:
        - net
      environment:
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_TICK_TIME=2000
        - ALLOW_ANONYMOUS_LOGIN=yes

    nifi:
      image: apache/nifi:1.15.3
      restart: always
      hostname: nifi
      container_name: nifi
      ports:
        - 8081:8080
      environment:
        - NIFI_WEB_HTTP_PORT=8080
        - NIFI_CLUSTER_IS_NODE=false
        - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
        - NIFI_ZK_CONNECT_STRING=zookeeper:2181
        - NIFI_ELECTION_MAX_WAIT=1 min
      networks:
        - net
      depends_on:
        - zookeeper
